const KEY='voya-v4';
const LEGACY='voya-v3';
const IMAGE_CACHE_DB='voya-packing-images-v1';
const IMAGE_CACHE_STORE='images';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(36).slice(2);
const emptyTrip=()=>({id:uid(),name:'',destination:'',startDate:'',endDate:'',type:'leisure',members:[],activities:[],customActivities:[],stops:[],packing:[],shared:[],outfits:[],createdAt:Date.now(),updatedAt:Date.now()});
let store=loadStore();
let currentPage='trips';
let packCategory='clothes';
let packSubcategory='tops';
let packSortable=null;
let packPerson='You';
let outfitPerson='You';
let outfitDraftItemIds=[];
let outfitEditingId='';
let outfitComposerSortables=[];
let imageCacheTimer=null;
let packDraftImage='';

const dict={en:{
'nav.trip':'Trip','nav.pack':'Pack','nav.outfits':'Looks','nav.shared':'Shared','trips.eyebrow':'YOUR TRIPS','trips.title':'Where to next?','trips.subtitle':'Keep every trip, packing list and outfit plan in one place.','trips.new':'New trip',
'edit.title':'Trip details','edit.subtitle':'Start with the basics. You can change everything later.','edit.name':'Trip name','edit.destination':'Main destination','edit.start':'Start','edit.end':'End','edit.type':'Trip type',
'common.cancel':'Cancel','common.saveContinue':'Save & continue','common.back':'Back','common.save':'Save','common.edit':'Edit',
'members.title':'Travelers','members.subtitle':'Add only the people actually joining. Remove anyone anytime.','plans.title':'Plans & events','plans.subtitle':'Tap suggestions or add your own. Nothing is permanent.','plans.custom':'Add your own',
'trip.overview':'TRIP OVERVIEW','trip.days':'Days','trip.travelers':'Travelers','trip.packed':'Packed','trip.stops':'Stops','trip.addStop':'Add stop','trip.plans':'Plans','trip.travelersTitle':'Travelers','trip.pack':'Packing','trip.looks':'Outfits','trip.shared':'Shared','trip.delete':'Delete this trip',
'packing.title':'Packing list','packing.subtitle':'Tap a type to add it quickly. Tap any item to add a photo or more details.','packing.packed':' packed','packing.addExact':'Add custom item','packing.photo':'Photo (optional)','packing.itemName':'Specific name (optional)','packing.type':'Item type','packing.subcategory':'Clothing subcategory','packing.person':'Whose item?','packing.note':'Note / event (optional)','packing.choosePhoto':'Choose photo','packing.changePhoto':'Change photo',
'outfits.title':'Outfit plan','outfits.subtitle':'Build complete looks directly from the clothes in your packing list.','outfits.add':'Create a look','shared.title':'Shared items','shared.subtitle':"Decide who brings what so you don't duplicate things.",'stop.title':'Add stop','outfitModal.title':'Build a look','outfitModal.name':'Look name / event (optional)','outfitModal.date':'Date (optional)','outfitModal.build':'Your look','outfitModal.help':'Drag clothes into the look, or tap ＋. Drag selected pieces to reorder.','outfitModal.packed':'Packed clothes','outfitModal.note':'Notes (optional)'
},zh:{
'nav.trip':'行程','nav.pack':'行李','nav.outfits':'穿搭','nav.shared':'共享','trips.eyebrow':'我的旅行','trips.title':'下一站去哪？','trips.subtitle':'把每次旅行、行李清单和穿搭计划都放在一起。','trips.new':'新建旅行',
'edit.title':'旅行信息','edit.subtitle':'先填基础信息，之后所有内容都可以修改。','edit.name':'旅行名称','edit.destination':'主要目的地','edit.start':'开始','edit.end':'结束','edit.type':'旅行类型',
'common.cancel':'取消','common.saveContinue':'保存并继续','common.back':'返回','common.save':'保存','common.edit':'编辑',
'members.title':'同行人','members.subtitle':'只添加真正同行的人，之后随时可以删除。','plans.title':'活动 / Event','plans.subtitle':'点选推荐活动或自己新增，之后都能改。','plans.custom':'自己添加',
'trip.overview':'旅行总览','trip.days':'天数','trip.travelers':'同行人','trip.packed':'已打包','trip.stops':'地点','trip.addStop':'添加地点','trip.plans':'活动','trip.travelersTitle':'同行人','trip.pack':'行李','trip.looks':'穿搭','trip.shared':'共享','trip.delete':'删除这次旅行',
'packing.title':'行李清单','packing.subtitle':'点类型即可快速加入；点已添加的物品可补充图片或详细信息。','packing.packed':' 已打包','packing.addExact':'添加自定义物品','packing.photo':'图片（可选）','packing.itemName':'具体名称（可选）','packing.type':'物品类型','packing.subcategory':'衣服子分类','packing.person':'谁的单品？','packing.note':'备注 / 对应活动（可选）','packing.choosePhoto':'选择图片','packing.changePhoto':'更换图片',
'outfits.title':'穿搭计划','outfits.subtitle':'直接用行李清单里的衣服组合完整穿搭。','outfits.add':'创建穿搭','shared.title':'共享物品','shared.subtitle':'分配谁带什么，避免重复。','stop.title':'添加地点','outfitModal.title':'组合一套穿搭','outfitModal.name':'穿搭名称 / 活动（可选）','outfitModal.date':'日期（可选）','outfitModal.build':'这套穿搭','outfitModal.help':'把衣服拖入搭配区，或点击 ＋；已选单品可继续拖动排序。','outfitModal.packed':'已添加的衣服','outfitModal.note':'备注（可选）'
}};

const activitySuggestions=[['📷','Sightseeing','观光'],['🏖','Beach','海滩'],['🥾','Hiking','徒步'],['🍽','Dining','餐厅'],['🍸','Night out','夜生活'],['🏛','Museum','博物馆'],['🛍','Shopping','购物'],['🧘','Wellness','放松'],['💻','Work','工作'],['🍷','Wine tasting','品酒'],['🎵','Concert','演出'],['🚤','Boat day','出海']];
const categories={
clothes:{en:'Clothes',zh:'衣物',items:['T-shirt','Tank top','Shirt','Dress','Pants','Jeans','Shorts','Skirt','Sweater / cardigan','Jacket','Sleepwear','Underwear','Socks','Swimsuit']},
shoes:{en:'Shoes',zh:'鞋子',items:['Sneakers','Sandals','Heels','Flats','Hiking shoes','Flip-flops','Boots']},
toiletries:{en:'Toiletries',zh:'洗护',items:['Toothbrush','Toothpaste','Cleanser','Moisturizer','Sunscreen','Shampoo','Conditioner','Body wash','Makeup','Makeup remover','Hairbrush','Razor']},
electronics:{en:'Electronics',zh:'电子',items:['Phone charger','Power bank','Universal adapter','Camera','Camera charger','Earbuds','Watch charger','Laptop','Laptop charger']},
documents:{en:'Documents',zh:'证件',items:['Passport','Visa','ID','Flight tickets','Hotel confirmations','Travel insurance','Driver license','Credit cards','Cash']},
health:{en:'Health',zh:'健康',items:['Medication','Painkiller','Band-aids','Motion sickness pills','Allergy medicine','Vitamins','Contact lenses','Glasses']},
accessories:{en:'Accessories',zh:'配饰',items:['Sunglasses','Hat','Jewelry','Belt','Scarf','Handbag','Tote bag','Umbrella']}
};
const clothingSubcategories={
  tops:{en:'Tops',zh:'上装',items:['T-shirt','Tank top','Shirt','Blouse','Crop top','Sweater / cardigan','Hoodie']},
  bottoms:{en:'Bottoms',zh:'下装',items:['Pants','Jeans','Shorts','Skirt','Leggings']},
  outerwear:{en:'Outerwear',zh:'外套',items:['Jacket','Coat','Blazer','Trench coat','Rain jacket']},
  dresses:{en:'Dresses',zh:'连衣裙',items:['Dress','Mini dress','Midi dress','Maxi dress','Jumpsuit']},
  swimwear:{en:'Swimwear',zh:'泳衣',items:['Swimsuit','Bikini','Bikini top','Bikini bottom','Cover-up']},
  gym:{en:'Gym',zh:'Gym',items:['Sports bra','Workout top','Gym shorts','Workout leggings','Training set']}
};
const clothingKeywords={
  swimwear:['swimsuit','swimwear','bikini','cover-up','泳衣','比基尼'],
  gym:['gym','workout','sports bra','training set','activewear','运动','健身','瑜伽'],
  dresses:['dress','jumpsuit','连衣裙'],
  outerwear:['jacket','coat','blazer','trench','cardigan','外套','夹克','大衣','西装','风衣'],
  bottoms:['pants','jeans','shorts','skirt','leggings','sock','裤','裙','牛仔'],
  tops:['t-shirt','tank','shirt','blouse','crop','sweater','hoodie','sleepwear','underwear','top','上衣','吊带','衬衫','背心','毛衣','睡衣']
};
function itemSubcategory(item={}){if(item.subcat&&clothingSubcategories[item.subcat])return item.subcat;const value=String(item.type||item.name||'').toLowerCase();for(const [key,words] of Object.entries(clothingKeywords)){if(words.some(word=>value.includes(word)))return key}return'tops'}
function clothingSubcategoryLabel(key){const group=clothingSubcategories[key]||clothingSubcategories.tops;return store.lang==='en'?group.en:group.zh}
const sharedPreset=['Universal adapter','Sunscreen','Camera','Tripod','Hair dryer','First aid kit','Laundry detergent','Umbrella','Portable speaker','Snacks'];

function loadStore(){try{let s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.trips)return s;const old=JSON.parse(localStorage.getItem(LEGACY)||'null');if(old?.trips){old.trips.forEach(tr=>{tr.packing=(tr.packing||[]).map(x=>({id:x.id||uid(),name:x.name||x.label||'Item',type:x.type||x.name||'Item',cat:x.cat||'clothes',person:x.person||'You',note:x.note||'',image:x.image||'',packed:!!x.packed}))});s={...old};localStorage.setItem(KEY,JSON.stringify(s));return s}return{lang:localStorage.getItem('voya-lang')||'en',trips:[],activeTripId:null}}catch(e){return{lang:'en',trips:[],activeTripId:null}}}
function localCacheJson(){return JSON.stringify(store,(key,value)=>key==='image'&&typeof value==='string'&&value.startsWith('data:image/')?'':value)}
function openPackingImageCache(){return new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error('IndexedDB unavailable'));return}const request=indexedDB.open(IMAGE_CACHE_DB,1);request.onerror=()=>reject(request.error);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(IMAGE_CACHE_STORE))db.createObjectStore(IMAGE_CACHE_STORE,{keyPath:'key'})};request.onsuccess=()=>resolve(request.result)})}
async function cachePackingImages(){const records=[];store.trips?.forEach(tr=>tr.packing?.forEach(item=>{if(item.id&&typeof item.image==='string'&&item.image.startsWith('data:image/'))records.push({key:`${tr.id}::${item.id}`,tripId:tr.id,itemId:item.id,image:item.image,updatedAt:Date.now()})}));if(!records.length)return 0;let db;try{db=await openPackingImageCache();await new Promise((resolve,reject)=>{const tx=db.transaction(IMAGE_CACHE_STORE,'readwrite'),bucket=tx.objectStore(IMAGE_CACHE_STORE);records.forEach(record=>bucket.put(record));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});return records.length}catch(error){console.warn('Voyā image cache write failed',error);return 0}finally{db?.close()}}
function schedulePackingImageCache(){clearTimeout(imageCacheTimer);imageCacheTimer=setTimeout(()=>cachePackingImages(),80)}
async function restoreCachedPackingImages(){let db;try{db=await openPackingImageCache();const records=await new Promise((resolve,reject)=>{const tx=db.transaction(IMAGE_CACHE_STORE,'readonly'),request=tx.objectStore(IMAGE_CACHE_STORE).getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error)}),images=new Map(records.map(record=>[record.key,record.image]));let restored=0;store.trips?.forEach(tr=>tr.packing?.forEach(item=>{const cached=images.get(`${tr.id}::${item.id}`);if(!item.image&&!item.imageCleared&&cached){item.image=cached;restored++}}));if(restored&&['packing','outfits'].includes(currentPage)&&!document.querySelector('.modal-backdrop'))navigate(currentPage);return restored}catch(error){console.warn('Voyā image cache read failed',error);return 0}finally{db?.close()}}
function saveStore(show=false){const tr=currentTrip();if(tr)tr.updatedAt=Date.now();schedulePackingImageCache();try{localStorage.setItem(KEY,localCacheJson())}catch(error){console.warn('Voyā local metadata cache unavailable',error)}if(show)showSaved()}
function showSaved(){const el=document.getElementById('saveState');if(!el)return;el.textContent=store.lang==='en'?'Saved ✓':'已保存 ✓';setTimeout(()=>el.textContent='',1400)}
function currentTrip(){return store.trips.find(t=>t.id===store.activeTripId)||null}
function currentDisplayName(){return String(window.voyaCurrentUserName||'Alison').trim()||'Alison'}
function tripRoster(tr=currentTrip()){return tr?.cloudId&&window.voyaTripRosters?.[tr.cloudId]||null}
function ownerDisplayName(tr=currentTrip()){return tripRoster(tr)?.ownerName||currentDisplayName()}
function tripMemberNames(tr=currentTrip()){const manual=(tr?.members||[]).map(m=>m?.name).filter(Boolean),cloud=(tripRoster(tr)?.members||[]).map(m=>m?.name).filter(Boolean);return[...new Set([...manual,...cloud])].filter(name=>name!==ownerDisplayName(tr))}
function tripTravelerCount(tr=currentTrip()){const roster=tripRoster(tr),manual=1+(tr?.members?.length||0),cached=Number(tr?.cloudTravelerCount)||0;return roster?.count||Math.max(manual,cached,1)}
function t(k){return dict[store.lang][k]||k}
function applyTranslations(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-ph-en]').forEach(el=>el.placeholder=store.lang==='en'?el.dataset.phEn:el.dataset.phZh)}
function setLang(l){store.lang=l;localStorage.setItem('voya-lang',l);saveStore();document.getElementById('langToggle').textContent=l==='en'?'中':'EN';navigate(currentPage,true)}
function navigate(page){if(page!=='trips'&&!currentTrip()&&page!=='edit')return navigate('trips');currentPage=page;const tpl=document.getElementById(page+'Tpl');if(!tpl)return;const app=document.getElementById('app');app.innerHTML='';app.appendChild(tpl.content.cloneNode(true));const back=document.getElementById('globalBack');back.classList.toggle('hidden',page==='trips');back.onclick=smartBack;const nav=document.getElementById('bottomNav');const navPages=['trip','packing','outfits','shared'];nav.classList.toggle('hidden',!navPages.includes(page));document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));applyTranslations();hydrate(page);window.scrollTo({top:0,behavior:'instant'})}
function goTrips(){navigate('trips')}
function smartBack(){const map={edit:'trips',members:'edit',plans:'members',trip:'trips',packing:'trip',outfits:'trip',shared:'trip'};navigate(map[currentPage]||'trips')}
function hydrate(page){({trips:renderTrips,edit:renderEdit,members:renderMembers,plans:renderPlans,trip:renderTrip,packing:renderPacking,outfits:renderOutfits,shared:renderShared}[page]||(()=>{}))()}

function createTrip(){const tr=emptyTrip();store.trips.unshift(tr);store.activeTripId=tr.id;saveStore();navigate('edit')}
function openTrip(id){store.activeTripId=id;saveStore();navigate('trip')}
function editTrip(id){store.activeTripId=id;saveStore();navigate('edit')}
function renderTrips(){const el=document.getElementById('tripCards');if(!store.trips.length){el.innerHTML=`<div class="empty-state">${store.lang==='en'?'No trips yet. Create one to get started.':'还没有旅行，先新建一个吧。'}</div>`;return}el.innerHTML=store.trips.map(tr=>{const total=tr.packing.length,done=tr.packing.filter(x=>x.packed).length,pct=total?Math.round(done/total*100):0;return `<div class="trip-card"><div class="trip-card-top"><div><div class="eyebrow">${escapeHtml(formatRange(tr.startDate,tr.endDate))}</div><h3>${escapeHtml(tr.name||tr.destination||'Untitled trip')}</h3><p>📍 ${escapeHtml(tr.destination||'—')}</p></div><button class="ghost-btn" onclick="toggleTripMenu(event,'${tr.id}')">•••</button></div><div class="mini-stats"><span class="mini-stat">${calcDays(tr)} ${store.lang==='en'?'days':'天'}</span><span class="mini-stat">${tripTravelerCount(tr)} ${store.lang==='en'?'travelers':'人'}</span><span class="mini-stat">${pct}% ${store.lang==='en'?'packed':'已打包'}</span></div><div class="trip-actions"><button class="open" onclick="openTrip('${tr.id}')">${store.lang==='en'?'Open trip':'进入旅行'}</button><button class="edit" onclick="editTrip('${tr.id}')">${store.lang==='en'?'Edit':'编辑'}</button></div></div>`}).join('')}
function toggleTripMenu(e,id){document.querySelector('.menu')?.remove();const m=document.createElement('div');m.className='menu';m.innerHTML=`<button onclick="duplicateTrip('${id}')">${store.lang==='en'?'Duplicate trip':'复制旅行'}</button><button onclick="deleteTrip('${id}')">${store.lang==='en'?'Delete trip':'删除旅行'}</button>`;e.currentTarget.parentElement.appendChild(m)}
function duplicateTrip(id){const src=store.trips.find(t=>t.id===id);if(!src)return;const cp=JSON.parse(JSON.stringify(src));cp.id=uid();cp.name=(cp.name||cp.destination||'Trip')+(store.lang==='en'?' copy':' 副本');cp.createdAt=cp.updatedAt=Date.now();store.trips.unshift(cp);saveStore(true);renderTrips()}
function deleteTrip(id){if(!confirm(store.lang==='en'?'Delete this trip?':'确定删除这次旅行？'))return;store.trips=store.trips.filter(t=>t.id!==id);if(store.activeTripId===id)store.activeTripId=store.trips[0]?.id||null;saveStore(true);navigate('trips')}
function deleteCurrentTrip(){const tr=currentTrip();if(tr)deleteTrip(tr.id)}

function renderEdit(){const tr=currentTrip();tripName.value=tr.name;destination.value=tr.destination;startDate.value=tr.startDate;endDate.value=tr.endDate;const types=[['leisure','✈️','Leisure','休闲'],['business','💼','Business','商务'],['mixed','♡','Mixed','混合']];tripTypes.innerHTML=types.map(x=>`<button class="choice ${tr.type===x[0]?'active':''}" onclick="setTripType('${x[0]}')">${x[1]}<span>${store.lang==='en'?x[2]:x[3]}</span></button>`).join('')}
function setTripType(v){currentTrip().type=v;saveStore();renderEdit()}
function saveTripDetails(goNext=false){const tr=currentTrip();tr.name=tripName.value.trim();tr.destination=destination.value.trim();tr.startDate=startDate.value;tr.endDate=endDate.value;if(!tr.destination){showToast(store.lang==='en'?'Add a destination first':'请先填写目的地');return}if(tr.startDate&&tr.endDate&&tr.endDate<tr.startDate){showToast(store.lang==='en'?'End date must be after start date':'结束日期要晚于开始日期');return}saveStore(true);if(goNext)navigate('members')}
function cancelEdit(){const tr=currentTrip();if(!tr.destination&&!tr.name&&!tr.members.length&&!tr.packing.length){store.trips=store.trips.filter(x=>x.id!==tr.id);store.activeTripId=store.trips[0]?.id||null;saveStore()}navigate('trips')}

function renderMembers(){const tr=currentTrip(),cloudNames=new Set((tripRoster(tr)?.members||[]).map(m=>m.name));membersList.innerHTML=`<div class="member-row"><div class="avatar">${escapeHtml(ownerDisplayName(tr)[0]?.toUpperCase()||'A')}</div><div class="meta"><b>${escapeHtml(ownerDisplayName(tr))}</b><small>${store.lang==='en'?'Trip owner':'旅行创建者'}</small></div><span class="pill">${store.lang==='en'?'Owner':'创建者'}</span></div>`+tripMemberNames(tr).map(name=>{const i=tr.members.findIndex(m=>m.name===name),canRemove=i>=0&&!cloudNames.has(name);return `<div class="member-row"><div class="avatar">${escapeHtml(name[0]?.toUpperCase()||'?')}</div><div class="meta"><b>${escapeHtml(name)}</b></div>${canRemove?`<button class="delete-btn" onclick="removeMember(${i})">×</button>`:`<span class="pill">${store.lang==='en'?'Joined':'已加入'}</span>`}</div>`}).join('')}
function addMember(){const tr=currentTrip(),input=memberName,name=input.value.trim();if(!name)return;tr.members.push({name});input.value='';saveStore();renderMembers()}
function removeMember(i){const tr=currentTrip(),removed=tr.members[i]?.name;tr.members.splice(i,1);tr.shared.forEach(x=>{if(x.who===removed)x.who=''});tr.packing.forEach(x=>{if(x.person===removed)x.person='You'});saveStore();renderMembers()}
function saveMembers(){saveStore(true);navigate('plans')}

function renderPlans(){const tr=currentTrip();activityGrid.innerHTML=activitySuggestions.map(a=>`<button class="activity ${tr.activities.includes(a[1])?'active':''}" onclick="toggleActivity('${a[1]}')"><span class="icon">${a[0]}</span><small>${store.lang==='en'?a[1]:a[2]}</small></button>`).join('');renderSelectedActivities()}
function toggleActivity(name){const tr=currentTrip(),i=tr.activities.indexOf(name);i>=0?tr.activities.splice(i,1):tr.activities.push(name);saveStore();renderPlans()}
function addCustomActivity(){const tr=currentTrip(),input=customActivity,name=input.value.trim();if(!name)return;if(!tr.customActivities.includes(name))tr.customActivities.push(name);input.value='';saveStore();renderSelectedActivities()}
function allActivities(tr=currentTrip()){return[...tr.activities,...tr.customActivities]}
function renderSelectedActivities(){const tr=currentTrip(),all=allActivities(tr);selectedActivities.innerHTML=all.map(a=>`<span class="chip">${escapeHtml(a)}<button onclick="removeActivity('${encodeURIComponent(a)}')">×</button></span>`).join('')||`<div class="empty-state">${store.lang==='en'?'No plans selected yet.':'还没有活动。'}</div>`}
function removeActivity(encoded){const tr=currentTrip(),a=decodeURIComponent(encoded);tr.activities=tr.activities.filter(x=>x!==a);tr.customActivities=tr.customActivities.filter(x=>x!==a);saveStore();renderPlans()}
function savePlans(){const tr=currentTrip();if(!tr.stops.length&&tr.destination)tr.stops=[{city:tr.destination,start:tr.startDate,end:tr.endDate}];saveStore(true);navigate('trip')}

function renderTrip(){const tr=currentTrip();overviewName.textContent=tr.name||tr.destination||'Trip';overviewDates.textContent=formatRange(tr.startDate,tr.endDate);overviewDestination.textContent='📍 '+(tr.destination||'—');dayCount.textContent=calcDays(tr);memberCount.textContent=tripTravelerCount(tr);const total=tr.packing.length,done=tr.packing.filter(x=>x.packed).length;packCount.textContent=total?Math.round(done/total*100)+'%':'0%';renderStops();overviewActivities.innerHTML=allActivities(tr).map(a=>`<span class="chip plain">${escapeHtml(a)}</span>`).join('')||`<div class="empty-state">${store.lang==='en'?'No plans yet.':'还没有活动。'}</div>`;travelerChips.innerHTML=[ownerDisplayName(tr),...tripMemberNames(tr)].map(x=>`<span class="chip plain">${escapeHtml(x)}</span>`).join('')}
function calcDays(tr){if(!tr.startDate||!tr.endDate)return '—';return Math.max(1,Math.round((new Date(tr.endDate)-new Date(tr.startDate))/86400000)+1)}
function formatRange(a,b){if(!a&&!b)return store.lang==='en'?'Dates not set':'未设置日期';const f=d=>d?new Date(d+'T12:00:00').toLocaleDateString(store.lang==='en'?'en-US':'zh-CN',{month:'short',day:'numeric'}):'—';return `${f(a)} — ${f(b)}`}
function renderStops(){const tr=currentTrip();stopsList.innerHTML=tr.stops.map((s,i)=>`<div class="it-card"><div class="city-thumb">${escapeHtml((s.city||'?')[0].toUpperCase())}</div><div><b>${escapeHtml(s.city)}</b><small>${escapeHtml(formatRange(s.start,s.end))}</small></div><button class="delete-btn" onclick="removeStop(${i})">×</button></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'No stops yet.':'还没有地点。'}</div>`}
function openStopModal(){document.body.appendChild(document.getElementById('stopModalTpl').content.cloneNode(true));applyTranslations()}
function saveStop(){const tr=currentTrip(),city=stopCity.value.trim();if(!city)return;tr.stops.push({city,start:stopStart.value,end:stopEnd.value});saveStore(true);closeModalButton();renderTrip()}
function removeStop(i){currentTrip().stops.splice(i,1);saveStore();renderStops()}

function people(){const tr=currentTrip();return ['You',...tripMemberNames(tr)]}
function renderPacking(){const tr=currentTrip();if(!people().includes(packPerson))packPerson='You';renderPackPeople();renderCategoryTabs();renderClothingSubcategories();renderPresets();renderPackItems();updatePackProgress()}
function renderPackPeople(){const el=document.getElementById('packPeople');if(!el)return;el.innerHTML=people().map(p=>`<button class="${p===packPerson?'active':''}" onclick="packPerson='${escapeJs(p)}';renderPacking()">${escapeHtml(p==='You'?ownerDisplayName():p)}</button>`).join('')}
function setPackCategory(key){packCategory=key;if(packCategory==='clothes'&&!clothingSubcategories[packSubcategory])packSubcategory='tops';renderPacking()}
function renderCategoryTabs(){categoryTabs.innerHTML=Object.entries(categories).map(([k,v])=>`<button class="${k===packCategory?'active':''}" onclick="setPackCategory('${k}')">${store.lang==='en'?v.en:v.zh}</button>`).join('')}
function setPackSubcategory(key){if(!clothingSubcategories[key])return;packSubcategory=key;renderPacking()}
function renderClothingSubcategories(){const el=document.getElementById('clothingSubcategoryTabs');if(!el)return;el.classList.toggle('hidden',packCategory!=='clothes');el.innerHTML=packCategory==='clothes'?Object.entries(clothingSubcategories).map(([key,group])=>`<button class="${key===packSubcategory?'active':''}" onclick="setPackSubcategory('${key}')">${store.lang==='en'?group.en:group.zh}</button>`).join(''):''}
function renderPresets(){const c=packCategory==='clothes'?clothingSubcategories[packSubcategory]:categories[packCategory];presetBox.innerHTML=`<div class="preset-title">${store.lang==='en'?'Tap a type to add it instantly. Add details only when you want.':'点一下就直接加入；需要时再补充名称或图片。'}</div><div class="preset-chips">${c.items.map(type=>`<button type="button" onclick="addPackPreset('${encodeURIComponent(type)}')">＋ ${escapeHtml(type)}</button>`).join('')}</div>`}
function addPackPreset(encodedType){const tr=currentTrip();if(!tr)return;const type=decodeURIComponent(encodedType||'').trim();if(!type)return;tr.packing.push({id:uid(),name:type,type,person:packPerson,cat:packCategory,subcat:packCategory==='clothes'?packSubcategory:'',note:'',image:'',packed:false});saveStore(true);renderPacking()}
function visiblePackItems(){const tr=currentTrip();return tr.packing.filter(x=>x.cat===packCategory&&x.person===packPerson&&(packCategory!=='clothes'||itemSubcategory(x)===packSubcategory))}
function renderPackItems(){const list=visiblePackItems();packingList.innerHTML=list.length?`<div class="pack-grid">${list.map(x=>packCard(x)).join('')}</div>`:`<div class="empty-state">${store.lang==='en'?'No exact items added here yet. Tap a type above to add the actual piece.':'这里还没有具体单品。点上面的类型添加这次真正要带的那一件。'}</div>`;initPackSortable()}
function packCard(x){const person=x.person==='You'?ownerDisplayName():x.person,drag=`<button type="button" class="pack-drag-handle" aria-label="${store.lang==='en'?'Drag to reorder':'拖动排序'}">⋮⋮</button>`;if(!x.image)return `<article class="pack-card no-photo ${x.packed?'is-packed':''}" data-pack-id="${escapeHtml(x.id)}">${drag}<button type="button" class="pack-compact-main" onclick="editPackItem('${x.id}')"><span class="pack-compact-plus">＋</span><span class="pack-compact-name">${escapeHtml(x.name)}</span></button><label class="pack-compact-check" title="${store.lang==='en'?'Packed':'已打包'}"><input type="checkbox" ${x.packed?'checked':''} onchange="togglePack('${x.id}',this.checked)"><span>✓</span></label><button type="button" class="pack-compact-delete" onclick="removePack('${x.id}')" aria-label="${store.lang==='en'?'Delete':'删除'}">×</button></article>`;const detail=x.cat==='clothes'?clothingSubcategoryLabel(itemSubcategory(x))+' · '+(x.type||'Item'):(x.type||'Item');return `<article class="pack-card has-photo ${x.packed?'is-packed':''}" data-pack-id="${escapeHtml(x.id)}">${drag}<div class="pack-photo" onclick="editPackItem('${x.id}')"><img src="${x.image}" alt=""></div><div class="pack-card-body"><div class="pack-type">${escapeHtml(detail)} · ${escapeHtml(person)}</div><div class="pack-name">${escapeHtml(x.name)}</div>${x.note?`<div class="pack-note">${escapeHtml(x.note)}</div>`:''}<div class="pack-card-actions"><label class="pack-check"><input type="checkbox" ${x.packed?'checked':''} onchange="togglePack('${x.id}',this.checked)"><span>${store.lang==='en'?'Packed':'已打包'}</span></label><button type="button" onclick="editPackItem('${x.id}')">✎</button><button type="button" onclick="removePack('${x.id}')">×</button></div></div></article>`}
function initPackSortable(){if(packSortable){packSortable.destroy();packSortable=null}const grid=document.querySelector('.pack-grid');if(!grid||typeof Sortable==='undefined')return;packSortable=Sortable.create(grid,{animation:170,handle:'.pack-drag-handle',draggable:'[data-pack-id]',forceFallback:true,fallbackOnBody:true,fallbackTolerance:4,touchStartThreshold:4,ghostClass:'pack-sort-ghost',chosenClass:'pack-sort-chosen',onEnd:()=>reorderPackItems([...grid.querySelectorAll('[data-pack-id]')].map(el=>el.dataset.packId))})}
function reorderPackItems(ids){const tr=currentTrip();if(!tr||ids.length<2)return;const byId=new Map(tr.packing.map(item=>[item.id,item])),ordered=ids.map(id=>byId.get(id)).filter(Boolean),visible=new Set(ids);if(ordered.length!==ids.length)return;let i=0;tr.packing=tr.packing.map(item=>visible.has(item.id)?ordered[i++]:item);saveStore(true)}
function openPackItemModal(encodedType='',id=''){document.querySelector('.pack-item-modal')?.closest('.modal-backdrop')?.remove();const type=decodeURIComponent(encodedType||'');const tr=currentTrip();const item=id?tr.packing.find(x=>x.id===id):null;packDraftImage=item?.image||'';document.body.appendChild(document.getElementById('packItemModalTpl').content.cloneNode(true));document.body.classList.add('modal-open');applyTranslations();packItemId.value=item?.id||'';packItemType.value=item?.type||type;packItemName.value=item?.name||'';packItemNote.value=item?.note||'';packItemPerson.innerHTML=people().map(p=>`<option value="${escapeHtml(p)}" ${p===(item?.person||packPerson)?'selected':''}>${escapeHtml(p==='You'?ownerDisplayName():p)}</option>`).join('');const field=document.getElementById('packSubcategoryField'),select=document.getElementById('packItemSubcategory');if(field)field.classList.toggle('hidden',packCategory!=='clothes');if(select){const selected=itemSubcategory(item||{type});select.innerHTML=Object.entries(clothingSubcategories).map(([key,group])=>`<option value="${key}" ${key===selected?'selected':''}>${store.lang==='en'?group.en:group.zh}</option>`).join('')}updatePackPhotoPreview()}
function editPackItem(id){openPackItemModal('',id)}
function handlePackPhoto(input){const file=input.files?.[0];if(!file)return;compressImage(file,900,.72).then(data=>{packDraftImage=data;updatePackPhotoPreview()}).catch(()=>showToast(store.lang==='en'?'Could not read photo':'图片读取失败'))}
function updatePackPhotoPreview(){const box=document.getElementById('packPhotoPreview');if(!box)return;box.innerHTML=packDraftImage?`<img src="${packDraftImage}" alt=""><button type="button" class="photo-remove" onclick="event.preventDefault();event.stopPropagation();removeDraftPhoto()">×</button>`:`<div class="photo-empty">＋<small>${store.lang==='en'?'Add photo':'添加图片'}</small></div>`}
function removeDraftPhoto(){packDraftImage='';updatePackPhotoPreview()}
function compressImage(file,max=900,quality=.72){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{let w=img.width,h=img.height;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.src=reader.result};reader.readAsDataURL(file)})}
function savePackItem(){const tr=currentTrip();if(!tr)return;const id=document.getElementById('packItemId')?.value||'';const type=(document.getElementById('packItemType')?.value||'').trim()||(store.lang==='en'?'Item':'物品');const typedName=(document.getElementById('packItemName')?.value||'').trim(),name=typedName||type,person=document.getElementById('packItemPerson')?.value||'You',note=(document.getElementById('packItemNote')?.value||'').trim(),subcat=packCategory==='clothes'?(document.getElementById('packItemSubcategory')?.value||itemSubcategory({type})):'';if(id){const x=tr.packing.find(x=>x.id===id);if(x){const nextImage=packDraftImage||'',oldPath=x.imagePath||'',replacing=nextImage.startsWith('data:image/')&&nextImage!==x.image,clearing=!nextImage;Object.assign(x,{name,type,person,note,image:nextImage,imagePath:replacing||clearing?'':oldPath,pendingImageDelete:(replacing||clearing)&&oldPath?oldPath:'',imageCleared:clearing,cat:packCategory,subcat})}}else tr.packing.push({id:uid(),name,type,person,note,image:packDraftImage||'',imagePath:'',imageCleared:false,cat:packCategory,subcat,packed:false});packPerson=person;if(packCategory==='clothes')packSubcategory=subcat;saveStore(true);closeModalButton();renderPacking()}
function togglePack(id,v){const x=currentTrip().packing.find(x=>x.id===id);if(x)x.packed=v;saveStore();renderPacking()}
function removePack(id){const tr=currentTrip(),item=tr.packing.find(x=>x.id===id);if(item?.imagePath)tr.pendingImageDeletes=[...new Set([...(tr.pendingImageDeletes||[]),item.imagePath])];tr.packing=tr.packing.filter(x=>x.id!==id);saveStore();renderPacking()}
function updatePackProgress(){const tr=currentTrip(),done=tr.packing.filter(x=>x.packed).length,total=tr.packing.length;packProgressText.textContent=`${done} / ${total}`;packProgressBar.style.width=(total?Math.round(done/total*100):0)+'%'}
function quickCustomPack(){openPackItemModal('')}

function outfitPackingItems(tr=currentTrip()){return (tr?.packing||[]).filter(item=>item.cat==='clothes'&&item.person===outfitPerson)}
function outfitLookItems(outfit,tr=currentTrip()){const byId=new Map((tr?.packing||[]).map(item=>[item.id,item]));return (outfit?.itemIds||[]).map(id=>byId.get(id)).filter(Boolean)}
function outfitPieceVisual(item,selected=false){const photo=item.image?`<img src="${item.image}" alt="">`:`<span class="outfit-piece-letter">${escapeHtml((item.name||item.type||'?')[0].toUpperCase())}</span>`;return `<div class="outfit-piece ${selected?'selected':''}">${photo}<small>${escapeHtml(item.name||item.type||'Item')}</small></div>`}
function renderOutfits(){const tr=currentTrip();tr.outfits=tr.outfits||[];if(!people().includes(outfitPerson))outfitPerson='You';outfitTabs.innerHTML=people().map(p=>`<button class="${p===outfitPerson?'active':''}" onclick="outfitPerson='${escapeJs(p)}';renderOutfits()">${escapeHtml(p==='You'?ownerDisplayName():p)}</button>`).join('');const list=tr.outfits.filter(o=>o.person===outfitPerson);outfitCards.innerHTML=list.map(o=>{const pieces=outfitLookItems(o,tr),visual=pieces.length?`<div class="look-canvas outfit-look-grid">${pieces.map(item=>outfitPieceVisual(item)).join('')}</div>`:`<div class="look-canvas outfit-legacy-look">${escapeHtml(o.note||'♡')}</div>`;return `<div class="outfit-card"><div class="outfit-top"><div><small>${escapeHtml(o.date||'')}</small><br><b>${escapeHtml(o.title||'Look')}</b></div><div class="outfit-card-actions"><button type="button" onclick="openOutfitModal('${o.id}')">${store.lang==='en'?'Edit':'编辑'}</button><button class="delete-btn" onclick="removeOutfit('${o.id}')">×</button></div></div>${visual}${pieces.length&&o.note?`<p class="outfit-note">${escapeHtml(o.note)}</p>`:''}</div>`}).join('')||`<div class="empty-state">${store.lang==='en'?'No looks yet. Use your packed clothes to build one.':'还没有穿搭。直接用已添加的衣服组合一套吧。'}</div>`}
function destroyOutfitComposerSortables(){outfitComposerSortables.forEach(sortable=>sortable?.destroy?.());outfitComposerSortables=[]}
function toggleOutfitItem(id){const i=outfitDraftItemIds.indexOf(id);if(i>=0)outfitDraftItemIds.splice(i,1);else outfitDraftItemIds.push(id);renderOutfitComposer()}
function removeOutfitDraftItem(id){outfitDraftItemIds=outfitDraftItemIds.filter(itemId=>itemId!==id);renderOutfitComposer()}
function syncOutfitDraftOrder(){const zone=document.getElementById('outfitDropZone');if(!zone)return;outfitDraftItemIds=[...zone.querySelectorAll('[data-item-id]')].map(el=>el.dataset.itemId)}
function renderOutfitComposer(){const wardrobe=document.getElementById('outfitWardrobe'),zone=document.getElementById('outfitDropZone');if(!wardrobe||!zone)return;destroyOutfitComposerSortables();const items=outfitPackingItems(),byId=new Map(items.map(item=>[item.id,item]));outfitDraftItemIds=outfitDraftItemIds.filter(id=>byId.has(id));wardrobe.innerHTML=items.length?items.map(item=>`<div class="outfit-picker-card ${outfitDraftItemIds.includes(item.id)?'is-selected':''}" data-item-id="${escapeHtml(item.id)}"><div class="outfit-picker-media">${item.image?`<img src="${item.image}" alt="">`:`<span>${escapeHtml((item.name||item.type||'?')[0].toUpperCase())}</span>`}<button type="button" class="outfit-picker-add" onclick="toggleOutfitItem('${escapeJs(item.id)}')">${outfitDraftItemIds.includes(item.id)?'✓':'＋'}</button><button type="button" class="outfit-drag-grip" aria-label="Drag">⋮⋮</button></div><small>${escapeHtml(item.name||item.type||'Item')}</small><em>${escapeHtml(clothingSubcategoryLabel(itemSubcategory(item)))}</em></div>`).join(''):`<div class="outfit-picker-empty">${store.lang==='en'?'No clothes for this traveler yet. Add clothes in Pack first.':'这个人的行李中还没有衣服，请先去「行李」添加。'}</div>`;zone.innerHTML=outfitDraftItemIds.length?outfitDraftItemIds.map(id=>{const item=byId.get(id);return `<div class="outfit-selected-piece" data-item-id="${escapeHtml(id)}"><div class="outfit-selected-media">${item.image?`<img src="${item.image}" alt="">`:`<span>${escapeHtml((item.name||item.type||'?')[0].toUpperCase())}</span>`}<button type="button" onclick="removeOutfitDraftItem('${escapeJs(id)}')">×</button></div><small>${escapeHtml(item.name||item.type||'Item')}</small><span class="outfit-selected-grip">⋮⋮</span></div>`}).join(''):`<div class="outfit-drop-empty">${store.lang==='en'?'Drag clothes here or tap ＋ below':'把衣服拖到这里，或点下面的 ＋'}</div>`;if(typeof Sortable!=='undefined'&&items.length){outfitComposerSortables.push(new Sortable(wardrobe,{group:{name:'voya-look',pull:'clone',put:false},sort:false,handle:'.outfit-drag-grip',animation:160,delay:180,delayOnTouchOnly:true,touchStartThreshold:4}));outfitComposerSortables.push(new Sortable(zone,{group:{name:'voya-look',pull:false,put:true},handle:'.outfit-selected-piece',animation:160,onAdd:event=>{const id=event.item?.dataset?.itemId;event.item?.remove();if(id&&!outfitDraftItemIds.includes(id))outfitDraftItemIds.push(id);renderOutfitComposer()},onEnd:()=>{syncOutfitDraftOrder()}}))}}
function openOutfitModal(id=''){document.querySelector('.outfit-builder-modal')?.closest('.modal-backdrop')?.remove();const tr=currentTrip(),outfit=id?tr.outfits.find(o=>o.id===id):null;outfitEditingId=outfit?.id||'';outfitDraftItemIds=[...(outfit?.itemIds||[])];document.body.appendChild(document.getElementById('outfitModalTpl').content.cloneNode(true));document.body.classList.add('modal-open');applyTranslations();document.getElementById('outfitId').value=outfitEditingId;document.getElementById('outfitTitle').value=outfit?.title||'';document.getElementById('outfitDate').value=outfit?.date||'';document.getElementById('outfitNote').value=outfit?.note||'';renderOutfitComposer()}
function saveOutfit(){const tr=currentTrip(),titleInput=document.getElementById('outfitTitle'),dateInput=document.getElementById('outfitDate'),noteInput=document.getElementById('outfitNote'),title=titleInput?.value.trim()||'',note=noteInput?.value.trim()||'';if(!outfitDraftItemIds.length&&!title&&!note){showToast(store.lang==='en'?'Choose at least one clothing item.':'请至少选择一件衣服。');return}const existing=outfitEditingId?tr.outfits.find(o=>o.id===outfitEditingId):null,data={id:existing?.id||uid(),person:outfitPerson,title:title||(store.lang==='en'?`Look ${tr.outfits.length+1}`:`穿搭 ${tr.outfits.length+1}`),date:dateInput?.value||'',note,itemIds:[...outfitDraftItemIds]};if(existing)Object.assign(existing,data);else tr.outfits.push(data);saveStore(true);destroyOutfitComposerSortables();closeModalButton();renderOutfits()}
function removeOutfit(id){const tr=currentTrip();tr.outfits=tr.outfits.filter(o=>o.id!==id);saveStore();renderOutfits()}

function renderShared(){const tr=currentTrip();sharedPresets.innerHTML=`<div class="preset-title">${store.lang==='en'?'Quick add':'快速添加'}</div><div class="preset-chips">${sharedPreset.map(x=>`<button onclick="addSharedPreset('${escapeJs(x)}')">＋ ${escapeHtml(x)}</button>`).join('')}</div>`;sharedList.innerHTML=tr.shared.map((x,i)=>`<div class="shared-row"><input type="checkbox" ${x.packed?'checked':''} onchange="trSharedToggle(${i},this.checked)"><div class="grow"><b>${escapeHtml(x.name)}</b></div><select onchange="setSharedWho(${i},this.value)"><option value="">${store.lang==='en'?'Unassigned':'未分配'}</option>${people().map(p=>`<option value="${escapeHtml(p)}" ${x.who===p?'selected':''}>${escapeHtml(p==='You'?ownerDisplayName():p)}</option>`).join('')}</select><button class="delete-btn" onclick="removeShared(${i})">×</button></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'No shared items yet.':'还没有共享物品。'}</div>`}
function addSharedPreset(name){const tr=currentTrip();if(!tr.shared.some(x=>x.name===name))tr.shared.push({name,who:'',packed:false});saveStore();renderShared()}
function addSharedItem(){const input=sharedItemName,name=input.value.trim();if(!name)return;currentTrip().shared.push({name,who:'',packed:false});input.value='';saveStore();renderShared()}
function trSharedToggle(i,v){currentTrip().shared[i].packed=v;saveStore()}
function setSharedWho(i,v){currentTrip().shared[i].who=v;saveStore()}
function removeShared(i){currentTrip().shared.splice(i,1);saveStore();renderShared()}
function explicitSave(){saveStore(true)}

function finishModalClose(){if(!document.querySelector('.modal-backdrop'))document.body.classList.remove('modal-open')}
function closeModal(e){if(e.target===e.currentTarget){e.currentTarget.remove();finishModalClose()}}
function closeModalButton(){const modals=document.querySelectorAll('.modal-backdrop'),top=modals[modals.length-1];top?.remove();finishModalClose()}
function showToast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeJs(s=''){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}

document.getElementById('langToggle').onclick=()=>setLang(store.lang==='en'?'zh':'en');
document.querySelectorAll('#bottomNav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
document.getElementById('langToggle').textContent=store.lang==='en'?'中':'EN';
navigate('trips');
window.voyaImageCacheReady=(async()=>{await cachePackingImages();return restoreCachedPackingImages()})();
