const KEY='voya-v3';
const legacyKey='voya-state-v2';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(36).slice(2);
const emptyTrip=()=>({id:uid(),name:'',destination:'',startDate:'',endDate:'',type:'leisure',members:[],activities:[],customActivities:[],stops:[],packing:[],shared:[],outfits:[],createdAt:Date.now(),updatedAt:Date.now()});
let store=loadStore();
let currentPage='trips';
let editTripId=null;
let packCategory='clothes';
let outfitPerson='You';

const dict={en:{
'nav.trip':'Trip','nav.pack':'Pack','nav.outfits':'Looks','nav.shared':'Shared','trips.eyebrow':'YOUR TRIPS','trips.title':'Where to next?','trips.subtitle':'Keep every trip, packing list and outfit plan in one place.','trips.new':'New trip',
'edit.title':'Trip details','edit.subtitle':'Start with the basics. You can change everything later.','edit.name':'Trip name','edit.destination':'Main destination','edit.start':'Start','edit.end':'End','edit.type':'Trip type',
'common.cancel':'Cancel','common.saveContinue':'Save & continue','common.back':'Back','common.save':'Save','common.edit':'Edit',
'members.title':'Travelers','members.subtitle':'Add only the people actually joining. Remove anyone anytime.','plans.title':'Plans & events','plans.subtitle':'Tap suggestions or add your own. Nothing is permanent.','plans.custom':'Add your own',
'trip.overview':'TRIP OVERVIEW','trip.days':'Days','trip.travelers':'Travelers','trip.packed':'Packed','trip.stops':'Stops','trip.addStop':'Add stop','trip.plans':'Plans','trip.travelersTitle':'Travelers','trip.pack':'Packing','trip.looks':'Outfits','trip.shared':'Shared','trip.delete':'Delete this trip',
'packing.title':'Packing list','packing.subtitle':'Use presets for speed, then add anything unique to your trip.','packing.packed':' packed','outfits.title':'Outfit plan','outfits.subtitle':'Plan by person, date or event.','outfits.add':'Add outfit','shared.title':'Shared items','shared.subtitle':"Decide who brings what so you don't duplicate things.",'stop.title':'Add stop','outfitModal.title':'Add outfit'
},zh:{
'nav.trip':'行程','nav.pack':'行李','nav.outfits':'穿搭','nav.shared':'共享','trips.eyebrow':'我的旅行','trips.title':'下一站去哪？','trips.subtitle':'把每次旅行、行李清单和穿搭计划都放在一起。','trips.new':'新建旅行',
'edit.title':'旅行信息','edit.subtitle':'先填基础信息，之后所有内容都可以修改。','edit.name':'旅行名称','edit.destination':'主要目的地','edit.start':'开始','edit.end':'结束','edit.type':'旅行类型',
'common.cancel':'取消','common.saveContinue':'保存并继续','common.back':'返回','common.save':'保存','common.edit':'编辑',
'members.title':'同行人','members.subtitle':'只添加真正同行的人，之后随时可以删除。','plans.title':'活动 / Event','plans.subtitle':'点选推荐活动或自己新增，之后都能改。','plans.custom':'自己添加',
'trip.overview':'旅行总览','trip.days':'天数','trip.travelers':'同行人','trip.packed':'已打包','trip.stops':'地点','trip.addStop':'添加地点','trip.plans':'活动','trip.travelersTitle':'同行人','trip.pack':'行李','trip.looks':'穿搭','trip.shared':'共享','trip.delete':'删除这次旅行',
'packing.title':'行李清单','packing.subtitle':'优先用预设快速添加，再补充你自己的物品。','packing.packed':' 已打包','outfits.title':'穿搭计划','outfits.subtitle':'按人、日期或活动来规划。','outfits.add':'添加穿搭','shared.title':'共享物品','shared.subtitle':'分配谁带什么，避免重复。','stop.title':'添加地点','outfitModal.title':'添加穿搭'
}};
const activitySuggestions=[['📷','Sightseeing','观光'],['🏖','Beach','海滩'],['🥾','Hiking','徒步'],['🍽','Dining','餐厅'],['🍸','Night out','夜生活'],['🏛','Museum','博物馆'],['🛍','Shopping','购物'],['🧘','Wellness','放松'],['💻','Work','工作'],['🍷','Wine tasting','品酒'],['🎵','Concert','演出'],['🚤','Boat day','出海']];
const categories={
clothes:{en:'Clothes',zh:'衣物',items:['T-shirts','Tank tops','Shirts','Dresses','Pants','Jeans','Shorts','Skirts','Sweater / cardigan','Jacket','Sleepwear','Underwear','Socks','Swimsuit']},
shoes:{en:'Shoes',zh:'鞋子',items:['Sneakers','Sandals','Heels','Flats','Hiking shoes','Flip-flops']},
toiletries:{en:'Toiletries',zh:'洗护',items:['Toothbrush','Toothpaste','Cleanser','Moisturizer','Sunscreen','Shampoo','Conditioner','Body wash','Makeup','Makeup remover','Hairbrush','Razor']},
electronics:{en:'Electronics',zh:'电子',items:['Phone charger','Power bank','Universal adapter','Camera','Camera charger','Earbuds','Watch charger','Laptop','Laptop charger']},
documents:{en:'Documents',zh:'证件',items:['Passport','Visa','ID','Flight tickets','Hotel confirmations','Travel insurance','Driver license','Credit cards','Cash']},
health:{en:'Health',zh:'健康',items:['Medication','Painkiller','Band-aids','Motion sickness pills','Allergy medicine','Vitamins','Contact lenses','Glasses']},
accessories:{en:'Accessories',zh:'配饰',items:['Sunglasses','Hat','Jewelry','Belt','Scarf','Handbag','Tote bag','Umbrella']}
};
const sharedPreset=['Universal adapter','Sunscreen','Camera','Tripod','Hair dryer','First aid kit','Laundry detergent','Umbrella','Portable speaker','Snacks'];
function loadStore(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.trips)return s;const legacy=JSON.parse(localStorage.getItem(legacyKey)||'null');if(legacy?.trip&&(legacy.trip.destination||legacy.trip.name)){const trip={...emptyTrip(),...legacy.trip,members:legacy.members||[],activities:legacy.activities||[],customActivities:legacy.customActivities||[],stops:legacy.stops||[],packing:legacy.packing||[],shared:legacy.shared||[],outfits:legacy.outfits||[]};const migrated={lang:legacy.lang||'en',trips:[trip],activeTripId:trip.id};localStorage.setItem(KEY,JSON.stringify(migrated));return migrated}return{lang:localStorage.getItem('voya-lang')||'en',trips:[],activeTripId:null}}catch(e){return{lang:'en',trips:[],activeTripId:null}}}
function saveStore(show=false){const t=currentTrip();if(t)t.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(store));if(show)showSaved()}
function showSaved(){const el=document.getElementById('saveState');if(!el)return;el.textContent=store.lang==='en'?'Saved ✓':'已保存 ✓';setTimeout(()=>{el.textContent=''},1400)}
function currentTrip(){return store.trips.find(t=>t.id===store.activeTripId)||null}
function t(k){return dict[store.lang][k]||k}
function applyTranslations(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-ph-en]').forEach(el=>el.placeholder=store.lang==='en'?el.dataset.phEn:el.dataset.phZh)}
function setLang(l){store.lang=l;localStorage.setItem('voya-lang',l);saveStore();document.getElementById('langToggle').textContent=l==='en'?'中':'EN';navigate(currentPage,true)}
function goTrips(){navigate('trips')}
function navigate(page,replace=false){if(page!=='trips'&&!currentTrip()&&page!=='edit'){return navigate('trips')}currentPage=page;const tpl=document.getElementById(page+'Tpl');if(!tpl)return;const app=document.getElementById('app');app.innerHTML='';app.appendChild(tpl.content.cloneNode(true));const back=document.getElementById('globalBack');back.classList.toggle('hidden',page==='trips');back.onclick=()=>smartBack();const nav=document.getElementById('bottomNav');const navPages=['trip','packing','outfits','shared'];nav.classList.toggle('hidden',!navPages.includes(page));document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));applyTranslations();hydrate(page);window.scrollTo({top:0,behavior:'instant'})}
function smartBack(){const map={edit:'trips',members:'edit',plans:'members',trip:'trips',packing:'trip',outfits:'trip',shared:'trip'};navigate(map[currentPage]||'trips')}
function hydrate(page){if(page==='trips')renderTrips();if(page==='edit')renderEdit();if(page==='members')renderMembers();if(page==='plans')renderPlans();if(page==='trip')renderTrip();if(page==='packing')renderPacking();if(page==='outfits')renderOutfits();if(page==='shared')renderShared()}
function createTrip(){const tr=emptyTrip();store.trips.unshift(tr);store.activeTripId=tr.id;editTripId=tr.id;saveStore();navigate('edit')}
function openTrip(id){store.activeTripId=id;saveStore();navigate('trip')}
function editTrip(id){store.activeTripId=id;editTripId=id;saveStore();navigate('edit')}
function renderTrips(){const el=document.getElementById('tripCards');if(!store.trips.length){el.innerHTML=`<div class="empty-state">${store.lang==='en'?'No trips yet. Create one and make Voyā your travel command center.':'还没有旅行。先新建一个，把 Voyā 变成你的旅行控制台。'}</div>`;return}el.innerHTML=store.trips.map(tr=>{const total=tr.packing.length,done=tr.packing.filter(x=>x.packed).length,pct=total?Math.round(done/total*100):0;return `<div class="trip-card"><div class="trip-card-top"><div><div class="eyebrow">${escapeHtml(formatRange(tr.startDate,tr.endDate))}</div><h3>${escapeHtml(tr.name||tr.destination||'Untitled trip')}</h3><p>📍 ${escapeHtml(tr.destination||'—')}</p></div><button class="ghost-btn" onclick="toggleTripMenu(event,'${tr.id}')">•••</button></div><div class="mini-stats"><span class="mini-stat">${calcDays(tr)} ${store.lang==='en'?'days':'天'}</span><span class="mini-stat">${1+tr.members.length} ${store.lang==='en'?'travelers':'人'}</span><span class="mini-stat">${pct}% ${store.lang==='en'?'packed':'已打包'}</span></div><div class="trip-actions"><button class="open" onclick="openTrip('${tr.id}')">${store.lang==='en'?'Open trip':'进入旅行'}</button><button class="edit" onclick="editTrip('${tr.id}')">${store.lang==='en'?'Edit':'编辑'}</button></div></div>`}).join('')}
function toggleTripMenu(e,id){document.querySelector('.menu')?.remove();const m=document.createElement('div');m.className='menu';m.innerHTML=`<button onclick="duplicateTrip('${id}')">${store.lang==='en'?'Duplicate trip':'复制旅行'}</button><button onclick="deleteTrip('${id}')">${store.lang==='en'?'Delete trip':'删除旅行'}</button>`;e.currentTarget.parentElement.appendChild(m)}
function duplicateTrip(id){const src=store.trips.find(t=>t.id===id);if(!src)return;const cp=JSON.parse(JSON.stringify(src));cp.id=uid();cp.name=(cp.name||cp.destination||'Trip')+(store.lang==='en'?' copy':' 副本');cp.createdAt=Date.now();cp.updatedAt=Date.now();store.trips.unshift(cp);saveStore(true);renderTrips()}
function deleteTrip(id){if(!confirm(store.lang==='en'?'Delete this trip?':'确定删除这次旅行？'))return;store.trips=store.trips.filter(t=>t.id!==id);if(store.activeTripId===id)store.activeTripId=store.trips[0]?.id||null;saveStore(true);navigate('trips')}
function deleteCurrentTrip(){const tr=currentTrip();if(tr)deleteTrip(tr.id)}
function renderEdit(){const tr=currentTrip();tripName.value=tr.name;destination.value=tr.destination;startDate.value=tr.startDate;endDate.value=tr.endDate;const types=[['leisure','✈️','Leisure','休闲'],['business','💼','Business','商务'],['mixed','♡','Mixed','混合']];tripTypes.innerHTML=types.map(x=>`<button class="choice ${tr.type===x[0]?'active':''}" onclick="setTripType('${x[0]}')">${x[1]}<span>${store.lang==='en'?x[2]:x[3]}</span></button>`).join('')}
function setTripType(v){currentTrip().type=v;saveStore();renderEdit()}
function saveTripDetails(goNext=false){const tr=currentTrip();tr.name=tripName.value.trim();tr.destination=destination.value.trim();tr.startDate=startDate.value;tr.endDate=endDate.value;if(!tr.destination){showToast(store.lang==='en'?'Add a destination first':'请先填写目的地');return}if(tr.startDate&&tr.endDate&&tr.endDate<tr.startDate){showToast(store.lang==='en'?'End date must be after start date':'结束日期要晚于开始日期');return}saveStore(true);if(goNext)navigate('members')}
function cancelEdit(){const tr=currentTrip();if(!tr.destination&&!tr.name&&!tr.members.length&&!tr.packing.length){store.trips=store.trips.filter(x=>x.id!==tr.id);store.activeTripId=store.trips[0]?.id||null;saveStore()}navigate('trips')}
function renderMembers(){const tr=currentTrip();membersList.innerHTML=`<div class="member-row"><div class="avatar">Y</div><div class="meta"><b>${store.lang==='en'?'You':'你'}</b><small>${store.lang==='en'?'Trip owner':'旅行创建者'}</small></div><span class="pill">${store.lang==='en'?'Owner':'创建者'}</span></div>`+tr.members.map((m,i)=>`<div class="member-row"><div class="avatar">${escapeHtml(m.name[0]?.toUpperCase()||'?')}</div><div class="meta"><b>${escapeHtml(m.name)}</b></div><button class="delete-btn" onclick="removeMember(${i})">×</button></div>`).join('')}
function addMember(){const tr=currentTrip(),input=memberName,name=input.value.trim();if(!name)return;tr.members.push({name});input.value='';saveStore();renderMembers()}
function removeMember(i){const tr=currentTrip(),removed=tr.members[i]?.name;tr.members.splice(i,1);tr.shared.forEach(x=>{if(x.who===removed)x.who=''});saveStore();renderMembers()}
function saveMembers(){saveStore(true);navigate('plans')}
function renderPlans(){const tr=currentTrip();activityGrid.innerHTML=activitySuggestions.map(a=>`<button class="activity ${tr.activities.includes(a[1])?'active':''}" onclick="toggleActivity('${a[1]}')"><span class="icon">${a[0]}</span><small>${store.lang==='en'?a[1]:a[2]}</small></button>`).join('');renderSelectedActivities()}
function toggleActivity(name){const tr=currentTrip(),i=tr.activities.indexOf(name);i>=0?tr.activities.splice(i,1):tr.activities.push(name);saveStore();renderPlans()}
function addCustomActivity(){const tr=currentTrip(),input=customActivity,name=input.value.trim();if(!name)return;if(!tr.customActivities.includes(name))tr.customActivities.push(name);input.value='';saveStore();renderSelectedActivities()}
function allActivities(tr=currentTrip()){return[...tr.activities,...tr.customActivities]}
function renderSelectedActivities(){const tr=currentTrip(),el=selectedActivities,all=allActivities(tr);el.innerHTML=all.map(a=>`<span class="chip">${escapeHtml(a)}<button onclick="removeActivity('${encodeURIComponent(a)}')">×</button></span>`).join('')||`<div class="empty-state">${store.lang==='en'?'No plans selected yet.':'还没有活动。'}</div>`}
function removeActivity(enc){const tr=currentTrip(),a=decodeURIComponent(enc);tr.activities=tr.activities.filter(x=>x!==a);tr.customActivities=tr.customActivities.filter(x=>x!==a);saveStore();renderPlans()}
function savePlans(){const tr=currentTrip();if(!tr.stops.length&&tr.destination)tr.stops=[{city:tr.destination,start:tr.startDate,end:tr.endDate}];saveStore(true);navigate('trip')}
function renderTrip(){const tr=currentTrip();overviewName.textContent=tr.name||tr.destination||'My Trip';overviewDates.textContent=formatRange(tr.startDate,tr.endDate);overviewDestination.textContent='📍 '+(tr.destination||'—');dayCount.textContent=calcDays(tr);memberCount.textContent=1+tr.members.length;const total=tr.packing.length,done=tr.packing.filter(x=>x.packed).length;packCount.textContent=total?Math.round(done/total*100)+'%':'0%';renderStops();overviewActivities.innerHTML=allActivities(tr).map(a=>`<span class="chip">${escapeHtml(a)}</span>`).join('')||`<div class="empty-state">${store.lang==='en'?'No plans yet.':'还没有活动。'}</div>`;travelerChips.innerHTML=[store.lang==='en'?'You':'你',...tr.members.map(m=>m.name)].map(n=>`<span class="chip">${escapeHtml(n)}</span>`).join('')}
function calcDays(tr){if(!tr.startDate||!tr.endDate)return '—';return Math.max(1,Math.round((new Date(tr.endDate)-new Date(tr.startDate))/86400000)+1)}
function formatRange(a,b){if(!a&&!b)return store.lang==='en'?'Dates not set':'未设置日期';const f=d=>d?new Date(d+'T12:00:00').toLocaleDateString(store.lang==='en'?'en-US':'zh-CN',{month:'short',day:'numeric'}):'—';return `${f(a)} — ${f(b)}`}
function renderStops(){const tr=currentTrip();stopsList.innerHTML=tr.stops.map((s,i)=>`<div class="it-card"><div class="city-thumb">${escapeHtml((s.city||'?')[0].toUpperCase())}</div><div><b>${escapeHtml(s.city)}</b><small>${formatRange(s.start,s.end)}</small></div><button class="delete-btn" onclick="removeStop(${i})">×</button></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'Add cities or places as you build the itinerary.':'按行程逐个添加城市或地点。'}</div>`}
function openStopModal(){document.body.appendChild(stopModalTpl.content.cloneNode(true));applyTranslations()}
function saveStop(){const tr=currentTrip(),city=stopCity.value.trim();if(!city)return;tr.stops.push({city,start:stopStart.value,end:stopEnd.value});saveStore(true);closeModalButton();renderTrip()}
function removeStop(i){currentTrip().stops.splice(i,1);saveStore();renderStops()}
function categoryLabel(k){return store.lang==='en'?categories[k].en:categories[k].zh}
function renderPacking(){const tr=currentTrip();categoryTabs.innerHTML=Object.keys(categories).map(k=>`<button class="${k===packCategory?'active':''}" onclick="packCategory='${k}';renderPacking()">${categoryLabel(k)}</button>`).join('');const presets=categories[packCategory].items;presetBox.innerHTML=`<div class="preset-title">${store.lang==='en'?'QUICK ADD':'快速添加'}</div><div class="preset-chips">${presets.map(name=>{const added=tr.packing.some(x=>x.name===name&&x.cat===packCategory);return `<button class="preset-chip ${added?'added':''}" onclick="addPreset('${escapeJs(name)}')">${added?'✓ ':'＋ '}${escapeHtml(name)}</button>`}).join('')}</div>`;const items=tr.packing.filter(x=>x.cat===packCategory);packingList.innerHTML=items.map(item=>`<div class="check-row"><input type="checkbox" ${item.packed?'checked':''} onchange="togglePack('${item.id}',this.checked)"><span class="grow">${escapeHtml(item.name)}</span><small>${escapeHtml(categoryLabel(item.cat))}</small><button class="delete-btn" onclick="removePack('${item.id}')">×</button></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'Nothing in this category yet. Tap a preset above.':'这个分类还没有物品，点上面的预设快速添加。'}</div>`;updatePackProgress()}
function addPreset(name){const tr=currentTrip();if(tr.packing.some(x=>x.name===name&&x.cat===packCategory))return;tr.packing.push({id:uid(),name,cat:packCategory,packed:false});saveStore();renderPacking()}
function addPackingItem(){const tr=currentTrip(),input=packingItemName,name=input.value.trim();if(!name)return;tr.packing.push({id:uid(),name,cat:packCategory,packed:false});input.value='';saveStore();renderPacking()}
function togglePack(id,v){const x=currentTrip().packing.find(i=>i.id===id);if(x)x.packed=v;saveStore();updatePackProgress()}
function removePack(id){const tr=currentTrip();tr.packing=tr.packing.filter(x=>x.id!==id);saveStore();renderPacking()}
function updatePackProgress(){const tr=currentTrip(),done=tr.packing.filter(x=>x.packed).length,total=tr.packing.length;if(document.getElementById('packProgressText'))packProgressText.textContent=`${done} / ${total}`;if(document.getElementById('packProgressBar'))packProgressBar.style.width=(total?done/total*100:0)+'%'}
function explicitSave(){saveStore(true)}
function renderOutfits(){const tr=currentTrip(),people=['You',...tr.members.map(m=>m.name)];if(!people.includes(outfitPerson))outfitPerson='You';outfitTabs.innerHTML=people.map(p=>`<button class="${p===outfitPerson?'active':''}" onclick="outfitPerson='${escapeJs(p)}';renderOutfits()">${escapeHtml(p==='You'?(store.lang==='en'?'Me':'我'):p)}</button>`).join('');const list=tr.outfits.filter(o=>o.person===outfitPerson);outfitCards.innerHTML=list.map(o=>`<div class="outfit-card"><div class="outfit-top"><div><small>${escapeHtml(o.date||'')}</small><br><b>${escapeHtml(o.title)}</b></div><button class="delete-btn" onclick="removeOutfit('${o.id}')">×</button></div><div class="look-canvas">${escapeHtml(o.note||'♡')}</div></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'No looks yet. Add one when you have an idea.':'还没有穿搭，有想法时再添加。'}</div>`}
function openOutfitModal(){document.body.appendChild(outfitModalTpl.content.cloneNode(true));applyTranslations()}
function saveOutfit(){const title=outfitTitle.value.trim();if(!title)return;currentTrip().outfits.push({id:uid(),person:outfitPerson,title,date:outfitDate.value,note:outfitNote.value.trim()});saveStore(true);closeModalButton();renderOutfits()}
function removeOutfit(id){const tr=currentTrip();tr.outfits=tr.outfits.filter(x=>x.id!==id);saveStore();renderOutfits()}
function renderShared(){const tr=currentTrip();sharedPresets.innerHTML=`<div class="preset-title">${store.lang==='en'?'COMMON SHARED ITEMS':'常用共享物品'}</div><div class="preset-chips">${sharedPreset.map(n=>{const added=tr.shared.some(x=>x.name===n);return `<button class="preset-chip ${added?'added':''}" onclick="addSharedPreset('${escapeJs(n)}')">${added?'✓ ':'＋ '}${escapeHtml(n)}</button>`}).join('')}</div>`;sharedList.innerHTML=tr.shared.map(x=>`<div class="shared-row"><input type="checkbox" ${x.packed?'checked':''} onchange="toggleShared('${x.id}',this.checked)"><span class="grow">${escapeHtml(x.name)}</span><select class="assignee" onchange="assignShared('${x.id}',this.value)">${assigneeOptions(x.who)}</select><button class="delete-btn" onclick="removeShared('${x.id}')">×</button></div>`).join('')||`<div class="empty-state">${store.lang==='en'?'No shared items yet. Use a preset or add your own.':'还没有共享物品，点预设或自己添加。'}</div>`}
function assigneeOptions(selected){const names=['', 'You',...currentTrip().members.map(m=>m.name)];return names.map(n=>`<option value="${escapeHtml(n)}" ${n===selected?'selected':''}>${escapeHtml(n?(n==='You'?(store.lang==='en'?'Me':'我'):n):(store.lang==='en'?'Unassigned':'未分配'))}</option>`).join('')}
function addSharedPreset(name){const tr=currentTrip();if(tr.shared.some(x=>x.name===name))return;tr.shared.push({id:uid(),name,who:'',packed:false});saveStore();renderShared()}
function addSharedItem(){const input=sharedItemName,name=input.value.trim();if(!name)return;currentTrip().shared.push({id:uid(),name,who:'',packed:false});input.value='';saveStore();renderShared()}
function assignShared(id,who){const x=currentTrip().shared.find(i=>i.id===id);if(x)x.who=who;saveStore()}
function toggleShared(id,v){const x=currentTrip().shared.find(i=>i.id===id);if(x)x.packed=v;saveStore()}
function removeShared(id){const tr=currentTrip();tr.shared=tr.shared.filter(x=>x.id!==id);saveStore();renderShared()}
function closeModal(e){if(e.target.classList.contains('modal-backdrop'))e.target.remove()}
function closeModalButton(){document.querySelector('.modal-backdrop')?.remove()}
function showToast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1600)}
function escapeHtml(s=''){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function escapeJs(s=''){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
document.getElementById('langToggle').onclick=()=>setLang(store.lang==='en'?'zh':'en');document.querySelectorAll('#bottomNav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));document.addEventListener('click',e=>{if(!e.target.closest('.menu')&&!e.target.closest('.ghost-btn'))document.querySelector('.menu')?.remove()});document.getElementById('langToggle').textContent=store.lang==='en'?'中':'EN';navigate('trips');